---
# Default variables for startup_setup role
log_file: "/var/log/startup-script.log"
git_repo: "https://github.com/shushinc/shushportal.git"
apache_config_file: "/etc/apache2/sites-available/shushportal.conf"
supervisor_config_file: "/etc/supervisor/conf.d/portal-supervisor.conf"
composer_version: "2.1.8"
nginx_conf: "/etc/nginx/nginx.conf"
drupal_nginx_conf: "/etc/nginx/sites-enabled/drupal-nginx.conf"
db_name: "moriaty"
db_user: "devportal"
db_password: "pass"  
root_password: "pass" 
sql_file_path: "/tmp/zcs_new.sql"  # Path to the SQL file
salt_file: "/var/www/html/shushportal/private-files/salt.txt"
set_permission_file: "/var/www/html/shushportal/set-permissions.sh"
start_php_fpm: "/var/www/html/shushportal/scripts/start-php-fpm.sh"
drupal_supervisor: "/etc/drupal_supervisor.conf"
apigateway: "none"   #currently support only AWS, Kong only, if not set to  none

